#!/usr/bin/env bash
# Update package list and install nginx
apt-get update -y
apt-get install nginx -y
chown -R www-data:www-data /var/www/html
echo "Holberton School for the win!" > /var/www/html/index.html
service nginx restart
